<?php
// Bulk regression coverage with the existing simulated PDS. Maintainer: Uli.
require __DIR__ . '/run.php';
require __DIR__ . '/../app/bulk.php';
$config['data_dir'] = sys_get_temp_dir() . '/stuffer-bulk-' . bin2hex(random_bytes(5)); mkdir($config['data_dir'], 0700);
$state = initial_state(); $state['did'] = 'did:plc:test';
$_SESSION['pds'] = ['did' => $state['did'], 'url' => 'https://pds.example', 'access' => 'test', 'refresh' => 'test', 'refreshed' => time()];
$pub = new_item($state['did'], 'site.standard.publication'); $pub['record'] = ['$type' => 'site.standard.publication', 'url' => 'https://example.de', 'name' => 'Test']; $pub['cid'] = 'pub'; $pub['published_record'] = $pub['record']; $state['publication'] = $pub;
$mock['records'] = []; $mock['pages'] = []; $mock['writes'] = 0;
$xml = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.de/a?x=1&amp;y=2</loc></url><url><loc>https://example.de/a?x=1&amp;y=2</loc></url></urlset>';
check(sitemap_entries($xml)['urls'] === ['https://example.de/a?x=1&y=2'], 'Sitemap namespaces, entities and deduplication');
if (function_exists('gzencode')) check(sitemap_entries(gzencode($xml)) === sitemap_entries($xml), 'Gzip sitemap');
throws(static function () { sitemap_entries('<!DOCTYPE x [<!ENTITY x SYSTEM "file:///etc/passwd">]><urlset/>'); }, 'XML external entities rejected');
throws(static function () { sitemap_entries('<urlset>'); }, 'Malformed XML rejected');
throws(static function () use (&$state) { bulk_start($state, 'sitemap', 'https://foreign.de/map.xml'); }, 'Foreign sitemap rejected');
$mock['pages']['https://example.de/index.xml'] = ['status'=>200,'type'=>'application/xml','body'=>'<sitemapindex><sitemap><loc>https://example.de/map.xml</loc></sitemap><sitemap><loc>https://example.de/index.xml</loc></sitemap></sitemapindex>'];
$mock['pages']['https://example.de/map.xml'] = ['status'=>200,'type'=>'application/xml','body'=>'<urlset><url><loc>https://example.de/a</loc></url><url><loc>https://example.de/a</loc></url><url><loc>https://other.de/b</loc></url></urlset>'];
$mock['pages']['https://example.de/a'] = ['status'=>200,'type'=>'text/html','body'=>'<html><head><title>New title</title><meta name="keywords" content="A,B"></head><body><article>New text</article></body></html>'];
bulk_start($state, 'sitemap', 'https://example.de/index.xml'); $job_id = $state['bulk']['id'];
throws(static function () use (&$state) { bulk_step($state, 'stale'); }, 'Stale job ID rejected');
while ($state['bulk']['status'] === 'running') bulk_step($state, $job_id);
check(count($state['documents']) === 1 && $state['bulk']['cursor'] === 3, 'Index cycle and duplicate URL avoided, foreign URL excluded');
$id = array_key_first($state['documents']);
check(!$state['documents'][$id]['cid'] && !isset($state['documents'][$id]['record']['publishedAt']), 'Undated sitemap page retained as draft, no invented date');
$_POST = ['id'=>$id]; throws(static function () use (&$state) { handle_action('publish', $state); }, 'Undated draft cannot publish');
bulk_start($state, 'sitemap', 'https://example.de/map.xml'); while ($state['bulk']['status'] === 'running') bulk_step($state, $state['bulk']['id']);
check(count($state['documents']) === 1 && $state['bulk']['counts']['skip'] === 1, 'Existing URL skipped on repeat import');
$state['documents'][$id]['record']['publishedAt'] = '2026-09-18T00:00:00Z'; sync_item($state, $state['documents'][$id], 'put');
$old_uri = $state['documents'][$id]['uri'];
$mock['pages']['https://example.de/a']['body'] = '<html><head><title>Changed</title></head><body><article>Changed body</article></body></html>';
bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check($state['documents'][$id]['published_record']['title'] === 'Changed' && $state['documents'][$id]['uri'] === $old_uri, 'Bulk update publishes extracted content with stable AT-URI');
check($state['documents'][$id]['record']['publishedAt'] === '2026-09-18T00:00:00Z', 'Existing publication date retained if source omits it');
$before = $state['documents'][$id]; $body_before = $mock['pages']['https://example.de/a']['body'];
$state['selectors'] = selector_defaults(); $state['selectors']['textContent'] = ['#missing'];
bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check($state['documents'][$id] === $before && $state['bulk']['counts']['error'] === 1, 'Empty text extraction preserves existing record');
unset($state['selectors']);
$writes = $mock['writes']; bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check($mock['writes'] === $writes, 'Unchanged content does not write PDS again');
foreach ([301,403,429,500,503] as $status) {
    $before = $state['documents'][$id]; $mock['pages']['https://example.de/a']['status'] = $status;
    bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
    check($state['documents'][$id] === $before && $state['bulk']['counts']['error'] === 1, 'HTTP ' . $status . ' preserves existing item');
}
$mock['pages']['https://example.de/a']['status'] = 200; $mock['pages']['https://example.de/a']['body'] = '<title>After interrupt</title><article>New</article>'; $mock['drop'] = true;
bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check($state['documents'][$id]['pending'] !== null && $state['bulk']['counts']['error'] === 1, 'Interrupted PDS write retains recovery journal');
bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check($state['bulk']['counts']['skip'] === 1, 'Pending operations are not overwritten by bulk');
sync_item($state, $state['documents'][$id], 'put');
$mock['pages']['https://example.de/a']['status'] = 410; bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check(verify_item($state['documents'][$id], false, $state)['ok'], 'Removed HTTP 410 page passes link cleanup verification');
check($state['documents'][$id]['status'] === 'removed' && !$state['documents'][$id]['cid'], 'HTTP 410 deletes published PDS record');
$draft = new_item($state['did'], 'site.standard.document'); $draft['url'] = 'https://example.de/gone'; $state['documents']['gone'] = $draft;
bulk_start($state, 'update'); bulk_step($state, $state['bulk']['id']);
check(!isset($state['documents']['gone']), 'HTTP 404 deletes local draft');
check(read_state()['bulk']['status'] === 'done', 'Progress survives reload from JSON');
foreach (glob($config['data_dir'].'/*') as $file) unlink($file); rmdir($config['data_dir']);
echo "Bulk suite completed; $passed total checks including core suite.\n";
