<?php
// Front controller for standard-stuffer, created for Uli.
declare(strict_types=1);
$private_root = getenv('STANDARD_STUFFER_ROOT') ?: dirname(__DIR__);
require $private_root . '/app/bootstrap.php';
require $private_root . '/app/actions.php';
$error = ''; $notice = ''; $state = initial_state();
$page = is_string($_GET['page'] ?? null) ? $_GET['page'] : 'articles';
$id = is_string($_GET['id'] ?? null) ? $_GET['id'] : '';
if (!$setup_error) {
    $notice = $_SESSION['notice'] ?? ''; unset($_SESSION['notice']);
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        try {
            check_csrf(); $action = input_string($_POST, 'action', 50);
            if ($action === 'login') login_admin(input_password($_POST, 'password'));
            elseif (empty($_SESSION['admin'])) throw new RuntimeException('Bitte zuerst am Dashboard anmelden.');
            elseif ($action === 'logout') { $_SESSION = []; session_destroy(); header('Location: index.php', true, 303); exit; }
            else {
                $lock = storage_lock('dashboard');
                try {
                    $state = read_json($config['data_dir'] . '/dashboard.json', initial_state());
                    if (input_string($_POST, 'revision', 30) !== (string) $state['revision']) throw new RuntimeException('Der Datenstand hat sich in einem anderen Fenster geändert. Bitte neu laden und die Aktion erneut ausführen.');
                    $_SESSION['notice'] = handle_action($action, $state);
                } finally { flock($lock, LOCK_UN); fclose($lock); }
            }
            $destination = 'index.php?page=' . rawurlencode($page);
            if (in_array($action, ['analyze', 'reimport'], true)) $destination = 'index.php?page=editor&preview=1';
            if ($action === 'save_document') { $destination = 'index.php?page=editor&id=' . rawurlencode($_SESSION['open_id']); unset($_SESSION['open_id']); }
            elseif ($id !== '' && !in_array($action, ['purge', 'delete'], true)) $destination .= '&id=' . rawurlencode($id);
            if ($action === 'delete' || $action === 'purge' || $action === 'discard_preview') $destination = 'index.php';
            header('Location: ' . $destination, true, 303); exit;
        } catch (RuntimeException $e) { $error = $e->getMessage(); }
        catch (Throwable $e) { $error = 'Interner Fehler. Daten wurden nicht bestätigt. Schreibrechte und JSON-Sicherung prüfen; einen offenen PDS-Vorgang anschließend wiederholen.'; error_log('standard-stuffer: ' . get_class($e)); }
    }
    if (!empty($_SESSION['admin'])) {
        try { $state = read_state(); $state_valid = true; } catch (Throwable $e) { $state_valid = false; $error = 'JSON-Datenspeicher konnte nicht gelesen werden. Bitte die gesicherte dashboard.json wiederherstellen.'; }
        $download = $state_valid ? ($_GET['download'] ?? '') : '';
        if ($download === 'mapping') {
            try { $mapping_json = mapping_payload($state); header('Content-Type: application/json; charset=UTF-8'); header('Content-Disposition: attachment; filename="standard-stuffer-map.json"'); echo $mapping_json; exit; }
            catch (RuntimeException $e) { $error = $e->getMessage(); }
        }
        if ($download === 'website_helper') {
            header('Content-Type: text/plain; charset=UTF-8'); header('Content-Disposition: attachment; filename="standard-stuffer-links.php"'); readfile($private_root . '/website/standard-stuffer-links.php'); exit;
        }
        if ($download === 'verification' && $state['publication']) {
            header('Content-Type: text/plain; charset=UTF-8'); header('Content-Disposition: attachment; filename="site.standard.publication"'); echo $state['publication']['uri'] . "\n"; exit;
        }
        if ($download === 'backup') {
            header('Content-Type: application/json; charset=UTF-8'); header('Content-Disposition: attachment; filename="standard-stuffer-backup.json"'); echo json_encode_safe($state); exit;
        }
        if ($download === 'html' && isset($state['documents'][$id])) {
            header('Content-Type: text/plain; charset=UTF-8'); header('Content-Disposition: attachment; filename="article-source.html.txt"'); echo $state['documents'][$id]['source_html'] ?? ''; exit;
        }
    }
}
function form_start(string $action, array $state, string $id = ''): void {
    echo '<form method="post"><input type="hidden" name="csrf" value="' . h($_SESSION['csrf']) . '"><input type="hidden" name="revision" value="' . h($state['revision']) . '"><input type="hidden" name="action" value="' . h($action) . '"><input type="hidden" name="id" value="' . h($id) . '">';
}
function action_button(string $action, string $label, array $state, string $id = '', string $class = 'secondary'): void {
    form_start($action, $state, $id); echo '<button class="' . h($class) . '">' . h($label) . '</button></form>';
}
function field(string $name, string $label, string $value = '', string $type = 'text', bool $required = false, string $help = '', bool $readonly = false): void {
    echo '<div class="field"><label for="' . h($name) . '">' . h($label) . ($required ? ' <span class="required">*</span>' : '') . '</label>';
    $attributes = ' id="' . h($name) . '" name="' . h($name) . '"' . ($required ? ' required' : '') . ($readonly ? ' readonly' : '') . ($help ? ' aria-describedby="' . h($name) . '-help"' : '');
    if ($type === 'textarea') echo '<textarea' . $attributes . ' rows="' . ($name === 'textContent' ? '16' : '3') . '">' . h($value) . '</textarea>';
    else echo '<input' . $attributes . ' type="' . h($type) . '" value="' . h($value) . '"' . ($type === 'password' ? ' autocomplete="current-password"' : '') . '>';
    if ($help) echo '<small id="' . h($name) . '-help">' . h($help) . '</small>';
    echo '</div>';
}
function check_view(?array $check): void {
    if (!$check) { echo '<p class="status neutral">Noch nicht geprüft</p>'; return; }
    echo '<div class="check ' . ($check['ok'] ? 'good' : 'warning') . '"><strong>' . ($check['ok'] ? 'Prüfung erfolgreich' : 'Handlung erforderlich') . '</strong><p>' . h($check['message']) . '</p><small>Geprüft: ' . h($check['at']) . ' · Momentaufnahme</small></div>';
}
$publication = $state['publication'];
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>standard-stuffer · Publishing-Dashboard</title><link rel="stylesheet" href="assets/app.css"><link rel="icon" href="assets/icon.svg" type="image/svg+xml"><script src="assets/app.js" defer></script></head><body>
<a class="skip" href="#main">Zum Inhalt</a>
<header class="topbar"><a class="brand" href="index.php"><span class="brand-icon" aria-hidden="true">s<span>.</span></span><span>standard-stuffer<small>DEINE WEBSITE IM AT PROTOCOL</small></span></a><span class="edition">PHP + JSON</span></header>
<?php if ($setup_error): ?>
<main id="main" class="standalone"><p class="eyebrow">EINRICHTUNG</p><h1>Einmal vorbereiten.</h1><div class="check warning"><?=h($setup_error)?></div><section class="panel"><h2>So startest du</h2><ol class="steps"><li>Das Paket entpacken. Auf dem Server <code>php setup.php</code> ausführen und ein eigenes Dashboard-Passwort vergeben.</li><li>Den DocumentRoot auf den Ordner <code>public/</code> setzen. <code>app/</code>, <code>config.php</code> und <code>var/</code> bleiben außerhalb. Ohne SSH kannst du setup.php lokal ausführen und config.php mit angepasstem Datenpfad hochladen.</li><li>Dem PHP-Benutzer Lesezugriff auf config.php und Schreibzugriff auf var/ geben. HTTPS aktivieren.</li><li>Diese Seite neu laden und anmelden. Danach erklärt das Dashboard die Verbindung, Domain-Verifikation und Artikel-Veröffentlichung.</li></ol><p>Ausführliche Hinweise, auch für bestehendes Hosting: <strong>README.md im Paket</strong>.</p></section></main>
<?php elseif (empty($_SESSION['admin'])): ?>
<main id="main" class="standalone login"><p class="eyebrow">DEIN PUBLISHING-WERKZEUG</p><h1>Inhalte verbinden.<br>Kontrolle behalten.</h1><p class="lead">Ausgewählte Webseiten veröffentlichen, aktualisieren und verifizieren.</p><section class="panel"><h2>Dashboard öffnen</h2><?php if ($error): ?><p class="check warning" role="alert"><?=h($error)?></p><?php endif ?><?php form_start('login', $state); field('password', 'Dashboard-Passwort', '', 'password', true); ?><button>Anmelden</button></form><p class="muted">Das lokale Dashboard-Passwort ist unabhängig von deinem AT-Protocol-Konto.</p></section></main>
<?php else: ?>
<div class="layout"><aside class="sidebar"><nav aria-label="Hauptnavigation"><?php foreach (['articles' => 'Artikel', 'publication' => 'Website & Verifikation', 'selectors' => 'Extraktion', 'deployment' => 'Deployment', 'connection' => 'Verbindung', 'help' => 'Anleitung'] as $nav_page => $nav_label): ?><a href="?page=<?=h($nav_page)?>" <?=($page === $nav_page || ($page === 'editor' && $nav_page === 'articles')) ? 'aria-current="page"' : ''?>><?=h($nav_label)?></a><?php endforeach ?></nav><div class="sidebar-bottom"><p class="connection-dot"><?=!empty($_SESSION['pds']) ? 'PDS verbunden' : 'PDS nicht verbunden'?></p><small><?=h($_SESSION['pds']['handle'] ?? 'Verbindung zum Veröffentlichen nötig')?></small><?php action_button('logout', 'Abmelden', $state); ?></div></aside>
<main id="main" class="content">
<?php if ($error): ?><div class="check warning" role="alert"><?=h($error)?></div><?php endif ?>
<?php if ($notice): ?><div class="notice" role="status"><?=h($notice)?></div><?php endif ?>
<?php if ($page === 'connection'): ?>
<p class="eyebrow">SCHRITT 1</p><h1>Verbindung zum PDS</h1><p class="lead">Hier liegen später die Standard.site-Datensätze deines Accounts.</p>
<div class="two-columns"><section class="panel"><h2>Account verbinden</h2><?php form_start('connect', $state); field('pds', 'PDS oder Bluesky-Anmeldeserver', 'https://bsky.social', 'url', true); field('identifier', 'Handle oder DID', $_SESSION['pds']['handle'] ?? '', 'text', true); field('app_password', 'App-Passwort', '', 'password', true, 'Ein eigenes App-Passwort verwenden, nicht dein normales Kontopasswort.'); ?><button>Verbindung herstellen</button></form></section><section class="panel soft"><h2>Einmal vorbereiten</h2><ol class="steps"><li>Für Bluesky in den Einstellungen unter „Datenschutz und Sicherheit → App-Passwörter“ ein eigenes Passwort für standard-stuffer erzeugen. Bei anderen PDS den jeweiligen Anmeldeserver verwenden.</li><li>Handle und App-Passwort links eingeben. Bei Bluesky ermittelt das Dashboard aus der Anmeldung den eigentlichen PDS.</li><li>Danach unter <a href="?page=publication">Website & Verifikation</a> die Publication anlegen.</li></ol><p>Zugriffstoken liegen nur in der serverseitigen Sitzung. Das App-Passwort wird nicht gespeichert. Nach Sitzungsende erneut verbinden.</p><?php if ($state['did']): ?><p>Gebundener Account:</p><code class="wrap"><?=h($state['did'])?></code><?php endif ?><?php if (!empty($_SESSION['pds'])): ?><div class="actions"><?php action_button('disconnect', 'PDS-Verbindung trennen', $state); ?></div><?php endif ?></section></div>
<?php elseif ($page === 'publication'): ?>
<p class="eyebrow">SCHRITT 2</p><h1>Website & Verifikation</h1><p class="lead">Die Publication beschreibt deine Website. Eine öffentliche Datei bestätigt die Zuordnung.</p>
<div class="two-columns"><section class="panel"><h2>Publication</h2><?php form_start('publication', $state); field('url', 'Website-Adresse', $publication['record']['url'] ?? '', 'url', true, 'Ohne abschließenden Slash. Auch https://example.de/blog ist möglich.', !empty($publication['cid'])); field('name', 'Name der Website', $publication['record']['name'] ?? '', 'text', true); field('description', 'Beschreibung', $publication['record']['description'] ?? '', 'textarea'); ?><button><?=$publication && $publication['cid'] ? 'Publication aktualisieren' : 'Publication anlegen'?></button></form><?php if ($publication && $publication['pending']): ?><div class="check warning">Der letzte Vorgang ist noch offen. Keine neue Publication anlegen.</div><?php action_button('retry_publication', 'Offenen Vorgang wiederholen', $state); endif ?></section>
<section class="panel soft"><h2>Domain bestätigen</h2><?php if (!$publication): ?><p>Zuerst die Publication anlegen. Anschließend erscheinen hier die genaue Zieladresse und der Dateiinhalt.</p><?php else: ?>
<ol class="steps"><li>Unter dieser Adresse muss deine Website eine einfache Textantwort ausliefern:<code class="block"><?=h(verification_url($publication['record']['url']))?></code></li><li>Die Antwort enthält nur diese AT-URI, ohne HTML:<code class="block" id="publication-uri"><?=h($publication['uri'])?></code><div class="actions"><button class="secondary" type="button" data-copy="publication-uri">URI kopieren</button><a class="button secondary" href="?download=verification">Datei herunterladen</a></div></li><li>Die Datei im Ordner <code>.well-known</code> deiner Website ablegen. Für eine Publication in einem Unterverzeichnis muss die oben angezeigte Pfad-Erweiterung ebenfalls umgesetzt werden; dafür ggf. eine Serverroute verwenden.</li><li>Wenn die URL erreichbar ist, Prüfung starten. Die Datei bleibt dauerhaft bestehen.</li></ol>
<?php action_button('verify_publication', 'Domain-Verifikation prüfen', $state, '', 'primary'); check_view($publication['check']); endif ?></section></div>
<?php elseif ($page === 'deployment'): ?>
<?php require $private_root . '/app/deployment-view.php'; ?>
<?php elseif ($page === 'selectors'): ?>
<p class="eyebrow">EXTRAKTIONSREGELN</p><h1>Deine Seiten. Deine Selektoren.</h1><p class="lead">Von oben nach unten suchen. Der erste verwertbare Treffer gewinnt.</p><p class="check neutral">Seitenabruf: <?=empty($config['fetch_proxy']['url']) ? 'Direkt, ohne Proxy' : 'Über den konfigurierten HTTP(S)-Proxy'?>. Einstellungen im Abschnitt <code>fetch_proxy</code> der privaten config.php. PDS und Deployment verwenden eigene direkte Verbindungen.</p>
<section class="panel"><?php form_start('selectors', $state); ?><p>Selektoren auswählen, ergänzen und sortieren. Ohne JavaScript: ein CSS-Selektor pro Zeile.</p><p class="muted">Unterstützt: Elemente, <code>.klasse</code>, <code>#id</code>, <code>[attribut]</code>, <code>[attribut="wert"]</code>, Nachfahren und <code>&gt;</code>. Keine Pseudoklassen oder Kommagruppen.</p>
<?php foreach (['title' => 'Titel', 'description' => 'Beschreibung', 'publishedAt' => 'Veröffentlichungsdatum', 'cover_url' => 'Coverbild', 'textContent' => 'Artikeltext'] as $key => $label): ?><div class="selector-field"><label for="selectors-<?=h($key)?>"><?=h($label)?></label><textarea id="selectors-<?=h($key)?>" name="selectors[<?=h($key)?>]" rows="4" data-selector-list="<?=h($key)?>" data-presets="<?=h(json_encode(selector_defaults()[$key]))?>"><?=h(implode("\n", ($state['selectors'] ?? selector_defaults())[$key]))?></textarea></div><?php endforeach ?>
<div class="check neutral"><strong>Tags: ausschließlich Meta-Keywords</strong><p><code>&lt;meta name="keywords" content="Klima, Energie"&gt;</code> wird an Kommas getrennt. Kein Rückgriff auf Kategorien oder automatisch erfundene Tags.</p></div>
<?php field('image_hosts', 'Zusätzliche Bild-Domains', implode("\n", $state['image_hosts'] ?? []), 'textarea', false, 'Nur bei Bildern von einem CDN: eine genaue Domain pro Zeile, ohne https://. Die Website-Domain ist automatisch erlaubt.'); ?><button>Extraktionsregeln speichern</button></form></section>
<section class="panel soft"><h2>Wie wird ein Treffer gelesen?</h2><p>Titel und Beschreibung: <code>content</code>-Attribut, sonst Text. Datum: <code>content</code>, <code>datetime</code> oder Text, nur als gültiges ISO-Datum. Bild: Meta-Inhalt, <code>data-src</code>, <code>data-lazy-src</code>, <code>src</code>, <code>href</code> oder erster srcset-Kandidat. Ein Container-Selektor verwendet das erste darin enthaltene Bild.</p><p>Beim Text wird der erste nicht leere Inhaltsbereich übernommen. Navigation, Skripte, Formulare und ausgeblendete Elemente werden entfernt. Der Gewinner und das Ergebnis erscheinen vor jeder Übernahme in der Vorschau.</p><p>„Verwertbar“ beim Bild bedeutet eine gültige HTTPS-Bildadresse. Ein HTTP- oder Dateifehler beim späteren Bildabruf wird angezeigt und überspringt den gewählten Treffer nicht stillschweigend.</p></section>
<?php elseif ($page === 'editor'): ?>
<?php
$preview_mode = isset($_GET['preview']) && isset($_SESSION['preview']);
$item = $id !== '' ? ($state['documents'][$id] ?? null) : null;
$values = $preview_mode ? $_SESSION['preview'] : ($item ? array_merge($item['record'], ['url' => $item['url'], 'cover_url' => $item['cover_url'] ?? '', 'tags' => implode(', ', $item['record']['tags'] ?? [])]) : null);
if ($preview_mode) { $id = $values['id']; $item = $id !== '' ? ($state['documents'][$id] ?? null) : null; }
if ($error && ($_POST['action'] ?? '') === 'save_document' && $values) foreach (['title','description','publishedAt','textContent','tags','cover_url'] as $key) if (is_string($_POST[$key] ?? null)) $values[$key] = $_POST[$key];
?>
<p class="eyebrow"><?= $preview_mode ? 'VORSCHAU · NOCH NICHT ÜBERNOMMEN' : 'ARTIKEL BEARBEITEN' ?></p><h1><?= $preview_mode ? 'Ergebnis prüfen.' : 'Artikel verwalten.' ?></h1>
<?php if (!$values): ?><section class="panel"><p>Kein Artikel ausgewählt.</p><a href="index.php">Zur Artikelübersicht</a></section><?php else: ?>
<?php foreach ($values['warnings'] ?? [] as $warning): ?><div class="check warning"><?=h($warning)?></div><?php endforeach ?>
<div class="editor-grid"><section class="panel"><h2>Inhalt & Metadaten</h2><?php form_start('save_document', $state, $id); field('url', 'Artikel-Adresse', $values['url'], 'url', true, '', true); field('title', 'Titel', $values['title'] ?? '', 'text', true); field('description', 'Beschreibung', $values['description'] ?? '', 'textarea'); field('publishedAt', 'Veröffentlicht am', $values['publishedAt'] ?? '', 'text', true, 'YYYY-MM-DD oder ISO-Datum mit Zeitzone, z. B. 2026-09-18T10:00:00+02:00. Reine Datumswerte gelten als 00:00 UTC.'); field('tags', 'Tags aus Meta-Keywords', $values['tags'] ?? '', 'text', false, 'Beim Einlesen ausschließlich aus meta keywords. Im Entwurf bei Bedarf korrigierbar.'); field('cover_url', 'Coverbild-Adresse', $values['cover_url'] ?? '', 'url', false, 'JPEG, PNG, WebP oder GIF unter 1 MB. Leer lassen für keinen Cover-Upload.'); field('textContent', 'Artikeltext (Klartext)', $values['textContent'] ?? '', 'textarea'); ?><button>Entwurf speichern</button><p class="muted">Speichern veröffentlicht noch nichts. Bereits veröffentlichte Inhalte ändern sich erst nach „Veröffentlichen“.</p></form></section>
<aside class="editor-aside"><section class="panel soft"><h2>Extraktion</h2><?php $matches = $values['matches'] ?? ($item['matches'] ?? []); if (!$matches): ?><p>Keine gespeicherten Selektor-Treffer.</p><?php else: ?><dl class="matches"><?php foreach ($matches as $key => $match): ?><dt><?=h(['title'=>'Titel','description'=>'Beschreibung','publishedAt'=>'Datum','cover_url'=>'Coverbild','textContent'=>'Text'][$key] ?? $key)?></dt><dd><code><?=h($match)?></code></dd><?php endforeach ?></dl><?php endif ?><p>HTML wird lokal als Quellenauszug aufbewahrt. Für den PDS wird Klartext mit Absatzumbrüchen verwendet. Tabellen und komplexe Layouts bitte kontrollieren.</p><?php if ($item): ?><a href="?download=html&id=<?=h($id)?>">HTML-Quellenauszug herunterladen</a><?php endif ?><?php if ($preview_mode): ?><div class="actions"><?php action_button('discard_preview', 'Vorschau verwerfen', $state); ?></div><?php endif ?></section>
<?php if ($item && !$preview_mode): ?><section class="panel"><h2>Veröffentlichung</h2><p class="status"><?=h($item['pending'] ? 'Vorgang offen' : ($item['status'] === 'removed' ? 'Am PDS entfernt' : ($item['cid'] ? (($item['record'] != $item['published_record']) ? 'Lokale Änderungen vorhanden' : 'Am PDS veröffentlicht') : 'Lokaler Entwurf')))?></p><code class="block"><?=h($item['uri'])?></code>
<?php if ($item['status'] !== 'removed'): ?><div class="actions"><?php if (!$item['pending'] || $item['pending']['operation'] === 'put') action_button('publish', $item['pending'] ? 'Offenen Vorgang wiederholen' : 'Gespeicherten Stand veröffentlichen', $state, $id, 'primary'); if (!$item['pending']) action_button('reimport', 'Seite neu einlesen', $state, $id); ?></div><p class="muted">Die Buttons verwenden den gespeicherten Stand. Änderungen im Formular zuerst als Entwurf speichern.</p><?php endif ?>
<details><summary>Datensatz als JSON ansehen</summary><pre><?=h(json_encode_safe($item['record']))?></pre></details></section>
<?php if ($item['cid'] || $item['status'] === 'removed'): ?><section class="panel soft"><h2><?=$item['status'] === 'removed' ? 'Link entfernen' : 'Artikel verifizieren'?></h2><p><?=$item['status'] === 'removed' ? 'Die zentrale Zuordnung neu deployen oder diesen Link manuell entfernen. Anschließend prüfen.' : 'Bei zentraler Einbindung: die Zuordnung unter Deployment übertragen. Alternativ diesen Link einmal in den <head> deiner Originalseite einfügen. Anschließend hier prüfen.'?></p><code class="block" id="article-link"><?=h('<link rel="site.standard.document" href="' . $item['uri'] . '">')?></code><button class="secondary" type="button" data-copy="article-link">Link kopieren</button><div class="actions"><?php action_button('verify', $item['status'] === 'removed' ? 'Link-Entfernung prüfen' : 'Artikel-Verifikation prüfen', $state, $id); ?></div><?php check_view($item['check']); ?><p class="muted">Die Domain-Verifikation wird separat unter „Website & Verifikation“ geprüft.</p></section><?php endif ?>
<section class="panel danger-zone"><h2><?=$item['status'] === 'removed' ? 'Eintrag abschließen' : 'Artikel entfernen'?></h2><?php if ($item['status'] === 'removed'): ?><p>Nach erfolgreicher Prüfung der Link-Entfernung kannst du den Eintrag aus der Übersicht entfernen.</p><?php action_button('purge', 'Eintrag abschließen', $state, $id); else: ?><?php form_start('delete', $state, $id); ?><label class="checkbox"><input type="checkbox" name="confirm" value="yes" required> <?=$item['cid'] || $item['pending'] ? 'Diesen Datensatz am PDS löschen. Die Originalseite bleibt bestehen.' : 'Diesen lokalen Entwurf löschen.'?></label><button class="danger">Löschen bestätigen</button></form><?php endif ?></section>
<?php endif ?></aside></div><?php endif ?>
<?php elseif ($page === 'help'): ?>
<p class="eyebrow">ANLEITUNG</p><h1>Vom Artikel zum Datensatz.</h1><section class="panel"><ol class="steps"><li><strong>Verbinden:</strong> Unter „Verbindung“ mit deinem Handle und einem App-Passwort am PDS anmelden.</li><li><strong>Website anlegen:</strong> Unter „Website & Verifikation“ deine Publication erstellen. Die dort angezeigte Datei auf deiner Website bereitstellen und die Domain-Verifikation prüfen.</li><li><strong>Extraktion festlegen:</strong> Für die Struktur deiner Website die Selektoren auswählen und in die gewünschte Reihenfolge bringen. Der erste verwertbare Treffer gewinnt. Tags stammen aus Meta-Keywords.</li><li><strong>Artikel einlesen:</strong> Unter „Artikel“ die genaue HTTPS-Adresse eingeben. In der Vorschau Titel, Text, Datum, Tags und Cover kontrollieren. Als Entwurf speichern.</li><li><strong>Veröffentlichen:</strong> Den gespeicherten Entwurf zum PDS übertragen. Das ist ein öffentlicher Datensatz. Ein vorhandenes Coverbild wird als Blob hochgeladen.</li><li><strong>Artikel bestätigen:</strong> Den angezeigten Link manuell in den HTML-Kopf deiner Seite einfügen. Webseite hochladen, ggf. Cache leeren, dann die Artikel-Verifikation prüfen.</li><li><strong>Aktualisieren:</strong> „Seite neu einlesen“ erzeugt erst eine Vorschau. Diese prüfen, speichern und veröffentlichen. Die AT-URI und der vorhandene Link bleiben gleich.</li><li><strong>Löschen:</strong> PDS-Löschung bestätigen. Danach die zentrale Zuordnung neu deployen oder den Link manuell entfernen, Entfernung prüfen und den erledigten Eintrag abschließen.</li></ol></section>
<section class="panel soft"><h2>HTML, Klartext und Bilder</h2><p><code>textContent</code> ist laut Standard.site reiner Text. HTML bleibt als Quellenauszug lokal erhalten; es wird nie im Dashboard ausgeführt. <code>content</code> unterstützt typisierte eigene Inhaltsformate, aber kein universell verstandenes HTML-Format. Dieses Dashboard veröffentlicht deshalb interoperablen Klartext, keine erfundene HTML-Erweiterung.</p><p>Die erste gefundene HTTPS-Bildadresse gewinnt. Beim Veröffentlichen prüft das Dashboard Dateityp und Größe. Zu große Bilder bitte auf der Website verkleinern oder eine kleinere Bildadresse im Entwurf angeben. Ein fehlerhaftes Cover verhindert die Veröffentlichung; alternativ das Coverfeld leeren.</p><p>Es gibt keine Hintergrund-Synchronisation. Prüfungen zeigen den Zustand zum angezeigten Zeitpunkt. Weiterleitungen, JavaScript-Inhalte und passwortgeschützte Quellseiten werden nicht automatisch übernommen.</p></section>
<section class="panel"><h2>Sicherung & offene Vorgänge</h2><p>Die Sicherung enthält Publication, Artikel, HTML-Auszüge, Selektoren und Prüfstände; keine Zugangstoken oder Passwörter. Zum Wiederherstellen die gesicherte Datei bei gestopptem Dashboard als <code>var/dashboard.json</code> einspielen. Den bisherigen Stand vorher sichern.</p><a class="button secondary" href="?download=backup">JSON-Sicherung herunterladen</a><p>Bei einer unterbrochenen PDS-Übertragung bleibt der Vorgang gespeichert. Über „Offenen Vorgang wiederholen“ wird zuerst geprüft, ob er bereits angekommen ist. Externe Änderungen am PDS werden nicht still überschrieben.</p><p><a href="https://standard.site/docs/introduction/" target="_blank" rel="noopener noreferrer">Standard.site-Dokumentation</a> · <a href="https://standard.site/docs/verification/" target="_blank" rel="noopener noreferrer">Verifikation</a></p></section>
<?php else: ?>
<p class="eyebrow">PUBLISHING-ÜBERSICHT</p><div class="heading-row"><div><h1>Deine Artikel.</h1><p class="lead">Ausgewählt veröffentlicht. Jeder Schritt nachvollziehbar.</p></div><a class="button secondary" href="?download=backup">JSON sichern</a></div>
<?php $published_count = 0; $checked_count = 0; foreach ($state['documents'] as $doc) { if ($doc['cid']) $published_count++; if ($doc['cid'] && ($doc['check']['ok'] ?? false)) $checked_count++; } ?>
<div class="stats"><div><strong><?=count($state['documents'])?></strong><span>verwaltete Artikel</span></div><div><strong><?=$published_count?></strong><span>am PDS veröffentlicht</span></div><div><strong><?=$checked_count?></strong><span>zuletzt erfolgreich geprüft</span></div></div>
<?php if (!$publication || !$publication['cid']): ?><section class="panel soft"><h2>Starte mit deiner Website</h2><p>Verbinde zuerst deinen PDS und lege die Publication an. Danach kannst du Artikel hinzufügen.</p><div class="actions"><a class="button" href="?page=connection">1. Account verbinden</a><a class="button secondary" href="?page=publication">2. Website einrichten</a></div></section><?php else: ?>
<?php if (!mapping_is_deployed($state, $config['deployment'] ?? [])): ?><p class="check neutral">Zentrale Einbindung verwendet? <a href="?page=deployment">Aktuelle Zuordnung deployen</a>. Bei ausschließlich manuellen Links ist dieser Schritt nicht nötig.</p><?php endif ?>
<?php if (!($publication['check']['ok'] ?? false)): ?><div class="check warning">Die Domain ist noch nicht erfolgreich geprüft. <a href="?page=publication">Domain-Verifikation abschließen</a>.</div><?php endif ?>
<section class="panel"><h2>Artikel hinzufügen</h2><?php form_start('analyze', $state); ?><div class="import-row"><?php field('url', 'Öffentliche Artikel-URL', '', 'url', true); ?><button>Seite einlesen</button></div></form><p class="muted">Zuerst Vorschau, dann Entwurf. Einlesen veröffentlicht noch nichts.</p></section><?php endif ?>
<section class="panel article-list"><div class="list-heading"><h2>Verwaltete Seiten</h2><label class="search-label">Filtern <input type="search" id="article-search" placeholder="Titel oder URL"></label></div>
<?php if (!$state['documents']): ?><div class="empty"><span aria-hidden="true">↗</span><h3>Platz für deinen ersten Artikel.</h3><p>Nach der Website-Einrichtung oben eine URL eintragen.</p></div><?php else: ?><div class="table-wrap"><table><thead><tr><th scope="col">Artikel</th><th scope="col">Veröffentlichung</th><th scope="col">Verifikation</th><th scope="col">Aktion</th></tr></thead><tbody><?php foreach (array_reverse($state['documents'], true) as $doc_id => $doc): ?><tr data-article-row><td><strong><?=h($doc['record']['title'])?></strong><small class="url"><?=h($doc['url'])?></small></td><td><span class="status <?= $doc['pending'] || $doc['status'] === 'removed' ? 'warning' : '' ?>"><?=h($doc['pending'] ? 'Vorgang offen' : ($doc['status'] === 'removed' ? 'Link entfernen' : ($doc['cid'] ? ($doc['record'] != $doc['published_record'] ? 'Änderungen offen' : 'Veröffentlicht') : 'Entwurf')))?></span></td><td><?=h($doc['check'] ? ($doc['check']['ok'] ? ($doc['status'] === 'removed' ? 'Link entfernt' : 'Erfolgreich geprüft') : 'Handlung erforderlich') : 'Noch nicht geprüft')?><small><?=h($doc['check']['at'] ?? '')?></small></td><td><a class="button secondary" href="?page=editor&id=<?=h($doc_id)?>">Öffnen<span class="sr-only">: <?=h($doc['record']['title'])?></span></a></td></tr><?php endforeach ?></tbody></table></div><p id="no-results" hidden>Keine passenden Artikel gefunden.</p><?php endif ?></section>
<?php endif ?>
<footer class="footer">standard-stuffer · Deine Website im AT Protocol.<span>Version 1.1.0</span></footer>
</main></div><?php endif ?><div id="live-message" class="sr-only" aria-live="polite"></div></body></html>
